---
- name: generate crypto key
  become: true
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key

- name: generate crypto config
  become: true
  template:
    src: /etc/ansible/roles/kubernetes/templates/encryption_config.j2
    dest: /etc/ansible/roles/kubernetes/files/encryption-config.yaml
    mode: 0644
