---
- name: set up kubeconfig file for admin for remote access
  shell: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true --server=https://{{ cluster_public_ip }}:6443
  args:
    chdir: "/etc/ansible/roles/kubernetes/files/"

- name: set-credentials for kubeconfig file for admin
  shell: kubectl config set-credentials admin --client-certificate=admin.pem --client-key=admin-key.pem
  args:
    chdir: "/etc/ansible/roles/kubernetes/files/"

- name: set-context for kubeconfig file for admin
  shell: kubectl config set-context kubernetes-the-hard-way --cluster=kubernetes-the-hard-way --user=admin
  args:
    chdir: "/etc/ansible/roles/kubernetes/files/"

- name: use-contex for kubeconfig file for admin
  shell: kubectl config use-context kubernetes-the-hard-way
  args:
    chdir: "/etc/ansible/roles/kubernetes/files/"
